<?php

/**
 * Moe Ask Api
 * MoeAsk的api文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@moeask.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class DefaultController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation userGet
     *
     * 获取用户信息.
     *
     *
     * @return Http response
     */
    public function userGet()
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing userGet as a get method ?');
    }
    /**
     * Operation userLoginPost
     *
     * .
     *
     *
     * @return Http response
     */
    public function userLoginPost()
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing userLoginPost as a post method ?');
    }
}
