openapi: 3.0.1
info:
  contact:
    email: support@moeask.com
  description: MoeAsk的api文档
  license:
    name: AGPL 3.0
    url: https://www.gnu.org/licenses/agpl-3.0.html
  termsOfService: https://moeask.com/terms/
  title: Moe Ask Api
  version: 1.0.0
servers:
- url: https://api.moeask.com/v1
paths:
  /user:
    get:
      responses:
        "200":
          content: {}
          description: OK
      summary: 获取用户信息
  /user/login:
    post:
      responses:
        "200":
          content:
            '*/*':
              schema:
                type: object
          description: ""
components:
  schemas: {}
  securitySchemes:
    TokenAuth:
      description: 用于验证用户身份的token。通过登录获得。
      in: header
      name: Identity-Token
      type: apiKey
    OAuth:
      flows:
        authorizationCode:
          authorizationUrl: /oauth/authorize
          scopes:
            read:user: 读取用户信息
          tokenUrl: /oauth/token
      type: oauth2

