<?php

/**
 * Moe Ask Api
 * MoeAsk的api文档
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@moeask.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */

/**
 * get userGet
 * Summary: 获取用户信息
 * Notes: 

 */
Route::get('/v1/user', 'DefaultController@userGet');
/**
 * post userLoginPost
 * Summary: 
 * Notes: 
 * Output-Formats: [*_/_*]
 */
Route::post('/v1/user/login', 'DefaultController@userLoginPost');

